name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.6.5

  # Cupertino style icons
  cupertino_icons: ^1.0.2

  # For API Call
  http: ^1.0.0

  # Converting CSV data to List
  csv: ^5.0.2

  # For Lottie Animation
  lottie: ^2.3.2

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads
  google_mobile_ads: ^3.0.0

  # For firebase
  firebase_core: ^2.14.0

  # For Remote Config
  firebase_remote_config: ^4.2.3

  #connectivity_plus: ^5.0.2


  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/icons/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/icons/
    - assets/lottie/
    - assets/flags/
    - assets/text/privacy_policy.txt

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/sora/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/sora/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sora/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/sora/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/sora/Sora-Medium.ttf
          weight: 500          
        - asset: assets/fonts/sora/Sora-SemiBold.ttf
          weight: 600          
        - asset: assets/fonts/sora/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/sora/Sora-ExtraBold.ttf
          weight: 800                    